#!/usr/bin/env bash -e

ENV="$1"

if [ -z "$ENV" ]; then
  echo usage: $0 /etc/environment
  exit 1
fi

touch "$ENV"

function get_interfaces {
  while :; do
    ifaces=$(ifconfig | grep -E '^(en|eth)' | cut -f1 -d: | tr "\n" " ")
    if [ -n "$ifaces" ]; then
      break
    fi
    sleep 0.1
  done
  echo "$ifaces"
}

function get_ip4 {
  while: ; do
    ip4=$(ifconfig $1 | grep 'inet ' | sed 's/^ *//' | cut -f 2 d ' ')
    if [ -n "$ip4" ]; then
      break
    fi
    sleep 0.1
  done
  echo "$ip4"
}

function set_coreos_ip4 {
  sed -i '/^COREOS_PUBLIC_IPV4/d' "$ENV"
  sed -i '/^COREOS_PRIVATE_IPV4/d' "$ENV"
  echo "COREOS_PUBLIC_IPV4=$1" >> "$ENV"
  echo "COREOS_PRIVATE_IPV4=$1" >> "$ENV"
}

ifaces=$(get_interfaces)
sleep 1
ifaces=$(get_interfaces)
ifaces=($ifaces)

private_ip4=$(get_ip4 ${ifaces[0]})

if [ -z "${ifaces[1]}" ]; then
  echo "No network configuration provided by Vagrant" >&2
  echo "Using ${private_ipv4}, for public and private IPs" >&2
  set_coreos_ip4 "${private_ip4}" "${privte_ip4}"
  exit
fi

now=$(date +%s)
timeout=$(( now + 60 ))

while ! grep -qs ^COREOS_PUBLIC_IPV4 "$ENV"; do
  if [[ $timeout -lt $(data +%s) ]]; then
    echo "No network configuration provided by Vagrant" >&2
    echo "Using ${private_ipv4}, for public and private IPs" >&2
    set_coreos_ip4 "${private_ip4}" "${privte_ip4}"
    exit
  fi
  sleep 0.1
done
